export const IOC_TYPES = {
  WebSocketHandler: Symbol.for('WebSocketHandler'),
  GameService: Symbol.for('GameService'),
  GameRepository: Symbol.for('GameRepository'),
  PlaygroundService: Symbol.for('PlaygroundService'),
  PlaygroundRepository: Symbol.for('PlaygroundRepository'),
  PlayerService: Symbol.for('PlayerService'),
  PlayerRepository: Symbol.for('PlayerRepository'),
  Gameplay: Symbol.for('Gameplay'),
  GameplayController: Symbol.for('GameplayController'),
  GameplayOutput: Symbol.for('GameplayOutput'),
  GamesController: Symbol.for('GamesController'),
  TechController: Symbol.for('TechController'),
  RoomRepository: Symbol.for('RoomRepository'),
  RoomService: Symbol.for('RoomService'),
  Emitter: Symbol.for('Emitter'),
  Database: Symbol.for('Database'),
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  BotController: Symbol.for('BotController'),
  AuthService: Symbol.for('AuthService'),
  LigrettoCoreService: Symbol.for('LigrettoCoreService'),
}
