export const TYPES = {
  WebSocketHandler: Symbol.for('WebSocketHandler'),
  GameService: Symbol.for('GameService'),
  GameRepository: Symbol.for('GameRepository'),
  PlaygroundService: Symbol.for('PlaygroundService'),
  PlaygroundRepository: Symbol.for('PlaygroundRepository'),
  PlayerService: Symbol.for('PlayerService'),
  PlayerRepository: Symbol.for('PlayerRepository'),
  Gameplay: Symbol.for('Gameplay'),
  GameplayController: Symbol.for('GameplayController'),
  GamesController: Symbol.for('GamesController'),
  RoomRepository: Symbol.for('RoomRepository'),
  RoomService: Symbol.for('RoomService'),
  Emitter: Symbol.for('Emitter'),
  Database: Symbol.for('Database'),
}
