yarnPath: "/home/themezv/projects/ligretto/.yarn/releases/yarn-berry.js"

nodeLinker: "node-modules"

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: af2fbdf2a7ca3fbae3683b11a1c969f88271f6eb
npmScopes:
  memebattle:
    npmRegistryServer: "https://npm.pkg.github.com"

