version: '3.3'
services:
  ligretto-frontend:
    image: ghcr.io/memebattle/ligretto-frontend:latest
    environment:
      - REACT_APP_WEBSOCKET_HOST=https://api.ligretto.app:3005
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-backend:
    image: ghcr.io/memebattle/ligretto-backend:latest
    ports:
      - "3005:3005"
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-backend/key.pem
    environment:
      - LIGRETTO_CAS_KEY_PATH=/ligretto-backend/key.pem
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-ui:
    image: ghcr.io/memebattle/ligretto-ui:latest
    ports:
      - "3001:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
secrets:
  LIGRETTO_CAS_KEY:
    external: true
