version: '3.3'
services:
  ligretto-frontend:
    image: ghcr.io/memebattle/ligretto-frontend:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - "3000:80"
  ligretto-backend:
    image: ghcr.io/memebattle/ligretto-backend:latest
    ports:
      - "3005:3005"
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-backend/key.pem
    environment:
      - LIGRETTO_CAS_KEY_PAT=/ligretto-backend/key.pem
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-ui:
    image: ghcr.io/memebattle/ligretto-ui:latest
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10s
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 3
      ports:
        - "3001:80"
secrets:
  LIGRETTO_CAS_KEY:
    external: true
