version: '3.3'
services:
  node:
    image: themezv/memebattle-docker-repo:my-cas
    command: ["--only", "API"]
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - "${PORT}:${PORT}"
    networks:
      - cas_net
    environment:
      - USE_DOCKER
    secrets:
      - source: CAS_PRIVATE_KEY
        target: /keys/key
      - source: CAS_PUBLIC_KEY
        target: /keys/key.pub
    env_file:
      - .env
  redis:
    image: redis:alpine
    volumes:
      - cas_data_redis:/data/redis
    networks:
      - cas_net
  mongo:
    image: mongo:latest
    networks:
      - cas_net
    volumes:
      - cas_data_mongo:/data/db
  mongo_admin:
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - cas_net
    ports:
      - "${MONGO_ADMIN_PORT}:8081"
    environment:
      - ME_CONFIG_SITE_BASEURL=/mongo_admin
    env_file:
      - .env
  swagger:
    image: themezv/memebattle-docker-repo:my-cas
    command: ["--only", "SWAGGER"]
    ports:
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
    networks:
      - cas_net
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  swagger-ui:
    image: pentusha/swagger-ui-crossbuild
    ports:
      - "${SWAGGER_UI_PORT}:${PORT}"
    environment:
      - API_URL=https://cas.mems.fun/openapi
    networks:
      - cas_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  kue-worker:
    image: themezv/memebattle-docker-repo:my-cas
    command: ["--only", "KUE-WORKER"]
    networks:
      - cas_net
    secrets:
      - source: CAS_PRIVATE_KEY
        target: /keys/key
      - source: CAS_PUBLIC_KEY
        target: /keys/key.pub
    env_file:
      - .env
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
#  kue-ui:
#    image: themezv/memebattle-docker-repo:my-cas
#    command: ["--only", "KUE-UI"]
#    ports:
#      - "${KUE_UI_PORT}:${KUE_UI_PORT}"
#    networks:
#      - cas_net
#    deploy:
#      replicas: 1
#        update_config:
#          parallelism: 2
#          delay: 10s
#        restart_policy:
#          condition: on-failure
#          delay: 10s
#          max_attempts: 3
#      resources:
#        limits:
#          cpus: '0.2'
#    env_file:
#      - .env
  static-server:
    image: nginx:latest
    ports:
      - "${STATIC_SERVER_PORT}:80"
    volumes:
      - cas_data_media:/usr/share/nginx/html/media
    configs:
      - source: CAS_STATIC_CONFIG
        target: /etc/nginx/conf.d/default.conf
    env_file:
      - .env
networks:
  cas_net:
volumes:
  cas_data_redis:
  cas_data_mongo:
  cas_data_media:
secrets:
  CAS_PRIVATE_KEY:
    external: true
  CAS_PUBLIC_KEY:
    external: true
configs:
  CAS_STATIC_CONFIG:
    external: true
