packages:
  - packages/*
  - apps/*

catalog:
  '@adonisjs/assembler': 5.7.0
  '@adonisjs/core': 5.9.0
  '@adonisjs/lucid': 17.2.0
  '@adonisjs/repl': 3.1.11
  '@amplitude/analytics-browser': ^2.1.2
  '@codexsoft/dotenv-flow': ^3.3.5
  '@emotion/cache': 11.10.3
  '@emotion/react': 11.10.4
  '@emotion/server': ^11.4.0
  '@emotion/styled': 11.10.4
  '@jest/globals': ^29.7.0
  '@mui/icons-material': 7.3.7
  '@mui/material': 7.3.7
  '@mui/system': 7.3.7
  '@playwright/test': ^1.57.0
  '@radix-ui/react-dropdown-menu': ^2.0.4
  '@radix-ui/react-popover': ^1.0.7
  '@reduxjs/toolkit': 2.11.2
  '@sentry/browser': ^7.108.0
  '@sentry/integrations': ^7.108.0
  '@sentry/vite-plugin': ^2.16.0
  '@storybook/addon-actions': ^7.0.6
  '@storybook/addon-docs': ^7.0.6
  '@storybook/addon-essentials': ^7.0.6
  '@storybook/addon-links': ^7.0.6
  '@storybook/addon-viewport': ^7.0.6
  '@storybook/addons': ^7.0.6
  '@storybook/preset-scss': ^1.0.3
  '@storybook/react': ^7.0.6
  '@storybook/react-vite': ^7.0.6
  '@tailwindcss/typography': ^0.5.9
  '@types/amplitude-js': 8.16.2
  '@types/history': ^4.7.2
  '@types/lodash': ^4.17.21
  '@types/negotiator': ^0
  '@types/node': 24.9.2
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  '@typescript-eslint/eslint-plugin': 7.3.1
  '@typescript-eslint/parser': 7.3.1
  '@vitejs/plugin-react': 5.1.2
  '@vitest/coverage-v8': ^0.32.0
  amplitude-js: ^8.21.6
  autoprefixer: ^10.4.14
  axios: ^1.3.4
  clsx: ^1.2.1
  contentlayer: ^0.3.4
  cpx: ^1.5.0
  cross-env: ^7.0.3
  csstype: ^3.2.3
  date-fns: ^2.29.3
  email-validator: ^2.0.4
  eslint: 8.57.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-import: 2.29.1
  eslint-plugin-prettier: 5.1.3
  eslint-plugin-react: 7.34.1
  eslint-plugin-react-hooks: ^4.5.0
  eslint-plugin-storybook: ^0.6.11
  feed: ^4.2.2
  final-form: ^4.20.1
  history: ^5.3.0
  i18next: ^22.4.14
  i18next-resources-to-backend: ^1.1.3
  inversify: ^5.0.1
  jest: ^29.5.0
  jsdom: ^22.1.0
  lodash: ^4.17.21
  luxon: 3.2.1
  mock-socket: ^9.1.5
  nanoid: ^3.1.20
  negotiator: ^0.6.3
  next: ^14.0.1
  next-contentlayer: ^0.3.4
  nodemon: ^2.0.16
  npm-run-all: ^4.1.5
  pg: ^8.6.0
  pino-pretty: ^7.6.1
  playwright: ^1.57.0
  postcss: ^8.4.21
  prettier: 3.2.5
  prom-client: ^14.2.0
  proxy-addr: ^2.0.6
  react: ^18.2.0
  react-docgen-typescript-loader: ^3.7.2
  react-docgen-typescript-plugin: ^1.0.0
  react-dom: ^18.2.0
  react-dropzone: 14.3.8
  react-final-form: ^6.5.2
  react-hotkeys-hook: 5.2.1
  react-i18next: ^12.2.0
  react-redux: ^8.0.5
  react-router: ^6.8.1
  react-router-dom: ^6.8.1
  redux: 5.0.1
  redux-first-history: ^5.2.0
  reflect-metadata: ^0.1.13
  rehype-autolink-headings: ^6.1.1
  rehype-slug: ^5.1.0
  reselect: 5.1.1
  schema-dts: ^1.1.2
  server-only: ^0.0.1
  sharp: ^0.32.5
  socket.io: ^4.5.1
  socket.io-client: ^4.5.1
  source-map-support: ^0.5.19
  storybook: ^7.0.6
  stylelint: 16.2.1
  stylelint-config-prettier: ^9.0.5
  stylelint-prettier: 5.0.0
  tailwindcss: ^3.3.1
  ts-jest: ^29.1.2
  ts-node: ^10.9.1
  typescript: ^5.9.3
  unist-util-visit: ^4.1.2
  vite: 7.3.1
  vite-plugin-svgr: 4.5.0
  vite-tsconfig-paths: 6.0.5
  vitest: 4.0.18
  wait-on: ^7.0.1
  youch: ^2.2.2
  youch-terminal: ^1.1.1
