import { LIGRETTO_CORE_URL, LIGRETTO_GAMEPLAY_SOCKET_PORT } from '../config'

if (!LIGRETTO_GAMEPLAY_SOCKET_PORT || !LIGRETTO_CORE_URL) {
  console.error('!LIGRETTO_GAMEPLAY_SOCKET_PORT || !LIGRETTO_CORE_URL')
  process.exit(-1)
}
