const types = {
    FETCH_ROOMS_REQUEST: '@@main/FETCH_ROOMS_REQUEST',
    FETCH_ROOMS_SUCCESS: '@@main/FETCH_ROOMS_SUCCESS',
    FETCH_ROOMS_ERROR: '@@main/FETCH_ROOMS_ERROR',

    CREATE_ROOM_SUCCESS: '@@main/CREATE_ROOM_SUCCESS',
    CREATE_ROOM_ERROR: '@@main/CREATE_ROOM_ERROR',
    SELECT_USER: '@@main/SELECT_USER',

    NEW_ROOM_CREATED: '@@main/NEW_ROOM_CREATED',
    ROOM_CHANGED: '@@main/ROOM_CHANGED',
    ROOM_DELETED: '@@main/ROOM_DELETED',

    SHOW_NOTIFICATION: '@@main/SHOW_NOTIFICATION',
    HIDE_NOTIFICATION: '@@main/HIDE_NOTIFICATION',

};

export default types