export const teammate: string
export const name: string
export const photo: string
export const photoWrapper: string
export const icon: string
export const iconWrapper: string
export const socialNetworks: string
export const teammateInView: string
export const iconWrapper01: string
export const iconWrapper02: string
export const iconWrapper12: string
export const iconWrapper03: string
export const iconWrapper13: string
export const iconWrapper23: string
export const iconWrapper04: string
export const iconWrapper14: string
export const iconWrapper24: string
export const iconWrapper34: string
export const iconWrapper05: string
export const iconWrapper15: string
export const iconWrapper25: string
export const iconWrapper35: string
export const iconWrapper45: string
export const iconWrapper06: string
export const iconWrapper16: string
export const iconWrapper26: string
export const iconWrapper36: string
export const iconWrapper46: string
export const iconWrapper56: string
export const iconWrapper07: string
export const iconWrapper17: string
export const iconWrapper27: string
export const iconWrapper37: string
export const iconWrapper47: string
export const iconWrapper57: string
export const iconWrapper67: string
export const iconWrapper08: string
export const iconWrapper18: string
export const iconWrapper28: string
export const iconWrapper38: string
export const iconWrapper48: string
export const iconWrapper58: string
export const iconWrapper68: string
export const iconWrapper78: string
export const iconWrapper09: string
export const iconWrapper19: string
export const iconWrapper29: string
export const iconWrapper39: string
export const iconWrapper49: string
export const iconWrapper59: string
export const iconWrapper69: string
export const iconWrapper79: string
export const iconWrapper89: string
export const iconWrapper010: string
export const iconWrapper110: string
export const iconWrapper210: string
export const iconWrapper310: string
export const iconWrapper410: string
export const iconWrapper510: string
export const iconWrapper610: string
export const iconWrapper710: string
export const iconWrapper810: string
export const iconWrapper910: string
export const iconWrapper011: string
export const iconWrapper111: string
export const iconWrapper211: string
export const iconWrapper311: string
export const iconWrapper411: string
export const iconWrapper511: string
export const iconWrapper611: string
export const iconWrapper711: string
export const iconWrapper811: string
export const iconWrapper911: string
export const iconWrapper1011: string
