/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  HealthChecks: () => import('#controllers/HealthChecksController'),
  http: {
    Auth: () => import('#controllers/Http/AuthController'),
    Games: () => import('#controllers/Http/GamesController'),
    Users: () => import('#controllers/Http/UsersController'),
  },
}
