export const IOC_TYPES = {
  IWebSocketHandler: Symbol.for('IWebSocketHandler'),
  IGameService: Symbol.for('IGameService'),
  IGameRepository: Symbol.for('IGameRepository'),
  IPlaygroundService: Symbol.for('IPlaygroundService'),
  IPlaygroundRepository: Symbol.for('IPlaygroundRepository'),
  IPlayerService: Symbol.for('IPlayerService'),
  IPlayerRepository: Symbol.for('IPlayerRepository'),
  IGameplay: Symbol.for('IGameplay'),
  IGamesController: Symbol.for('IGamesController'),
  IDatabase: Symbol.for('IDatabase'),
  IUserRepository: Symbol.for('IUserRepository'),
  IUserService: Symbol.for('IUserService'),
  IController: Symbol.for('IController'),
  IAuthService: Symbol.for('IAuthService'),
  ILigrettoCoreService: Symbol.for('ILigrettoCoreService'),
}
