export const IOC_TYPES = {
  WebSocketHandler: Symbol.for('WebSocketHandler'),
  IGameService: Symbol.for('IGameService'),
  IGameRepository: Symbol.for('IGameRepository'),
  PlaygroundService: Symbol.for('PlaygroundService'),
  PlaygroundRepository: Symbol.for('PlaygroundRepository'),
  IPlayerService: Symbol.for('IPlayerService'),
  IPlayerRepository: Symbol.for('IPlayerRepository'),
  Gameplay: Symbol.for('Gameplay'),
  GameplayController: Symbol.for('GameplayController'),
  GamesController: Symbol.for('GamesController'),
  RoomRepository: Symbol.for('RoomRepository'),
  RoomService: Symbol.for('RoomService'),
  Emitter: Symbol.for('Emitter'),
  Database: Symbol.for('Database'),
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  BotController: Symbol.for('BotController'),
  AuthService: Symbol.for('AuthService'),
  LigrettoCoreService: Symbol.for('LigrettoCoreService'),
}
