export const IOC_TYPES = {
  IWebSocketHandler: Symbol.for('IWebSocketHandler'),
  IGameService: Symbol.for('IGameService'),
  IGameRepository: Symbol.for('IGameRepository'),
  IPlaygroundService: Symbol.for('IPlaygroundService'),
  IPlaygroundRepository: Symbol.for('IPlaygroundRepository'),
  IPlayerService: Symbol.for('IPlayerService'),
  IPlayerRepository: Symbol.for('IPlayerRepository'),
  IGameplay: Symbol.for('IGameplay'),
  GameplayController: Symbol.for('GameplayController'),
  GamesController: Symbol.for('GamesController'),
  RoomRepository: Symbol.for('RoomRepository'),
  RoomService: Symbol.for('RoomService'),
  Emitter: Symbol.for('Emitter'),
  Database: Symbol.for('Database'),
  IUserRepository: Symbol.for('IUserRepository'),
  IUserService: Symbol.for('IUserService'),
  BotController: Symbol.for('BotController'),
  IAuthService: Symbol.for('IAuthService'),
  ILigrettoCoreService: Symbol.for('ILigrettoCoreService'),
}
