//! Accounts — the identity root of CAS.
//!
//! An account id is the OIDC `sub`. Guests are ordinary rows
//! (`type = AccountType::Guest`) so sessions, `/me` and userinfo have a single
//! code path for guests and full accounts; a guest that registers a passkey is
//! upgraded in place, keeping its `sub` ([`upgrade_guest`], under [`lock`]).
//! See `docs/PLAN.md` and `docs/adr/0015-guest-upgrade.md`.

mod display_name;
mod email;
pub mod http;
pub mod management;
mod repository;

use time::OffsetDateTime;
use uuid::Uuid;

use crate::clients::ClientId;

pub use display_name::{DisplayName, DisplayNameError};
pub use email::{Email, EmailError, MAX_EMAIL_LENGTH};
pub use management::AccountManagement;
pub use repository::AccountRepository;
pub(crate) use repository::{
    count_created_by_client, get, insert, lock, next_guest_number, touch_last_seen, upgrade_guest,
};

/// What a guest's generated display name starts with: `Guest 42`, the number
/// drawn from a database sequence ([`next_guest_number`]) when the guest is
/// minted, so every guest row holds a name of its own that CAS's screens and
/// an operator can tell apart. Distinct by construction, not by a constraint:
/// display names are not unique (PLAN). The guest has not chosen it, so it is
/// never released to a client: the claims read a name through
/// [`Account::chosen_name`], which has none for a guest. The guest upgrade
/// replaces it with the name the person chooses. See
/// `docs/adr/0014-guest-accounts-and-the-guest-grant.md` (b).
pub const GUEST_DISPLAY_NAME_PREFIX: &str = "Guest";

/// Whether an account has credentials of its own.
///
/// Maps to the Postgres `account_type` enum; on the wire it is the same
/// lowercase word.
// `ToSchema` describes it in the OpenAPI document, being on the wire
// already (docs/LAYOUT.md, rule 1).
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    sqlx::Type,
    serde::Serialize,
    serde::Deserialize,
    utoipa::ToSchema,
)]
#[sqlx(type_name = "account_type", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum AccountType {
    /// Temporary identity created without any user interaction.
    Guest,
    /// Account with at least one credential (a passkey).
    Full,
}

/// A row of `accounts`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Account {
    /// Stable account id, exposed as the OIDC `sub`.
    pub id: Uuid,
    /// Non-unique: CAS has no username in v1. Always a valid [`DisplayName`]:
    /// validated when the row is decoded, so a row that was written or altered
    /// outside CAS and does not pass surfaces as a decode error instead of
    /// reaching a UI.
    pub display_name: DisplayName,
    pub r#type: AccountType,
    /// Optional and unverified in v1; the future recovery anchor. Written
    /// only through an [`Email`], but not re-validated when the row is
    /// decoded: nothing signs in with it, and a stricter rule later must
    /// not lock an account out of `/me` over a field it cannot fix from
    /// there.
    pub email: Option<String>,
    /// The client that minted this account through the guest grant; `None`
    /// for an account created through CAS's own UI. Provenance, not
    /// ownership: it stays when a guest is upgraded.
    pub created_by_client_id: Option<ClientId>,
    pub created_at: OffsetDateTime,
    /// Refreshed on activity; drives guest GC.
    pub last_seen_at: OffsetDateTime,
}

impl Account {
    /// The name the account holder chose: `Some` for a full account, `None`
    /// for a guest, whose `display_name` was generated for it
    /// ([`GUEST_DISPLAY_NAME_PREFIX`]). The one place that knows a guest's
    /// name is not one it chose; whatever releases a name to a client reads
    /// it here.
    pub fn chosen_name(&self) -> Option<&DisplayName> {
        match self.r#type {
            AccountType::Full => Some(&self.display_name),
            AccountType::Guest => None,
        }
    }
}

/// The values a caller supplies when creating an account. `created_at` and
/// `last_seen_at` are assigned by the database, when the row is written.
#[derive(Debug, Clone)]
pub struct NewAccount {
    /// Generated by CAS, not by the database: passkey registration hands the id
    /// to the authenticator as the WebAuthn user handle before the row exists.
    /// The handle is baked into the credential and can never change, and
    /// discoverable login gets it back as the account to sign in.
    /// Defaults to a fresh v4 uuid; [`NewAccount::with_id`] pins a chosen one.
    pub id: Uuid,
    pub display_name: DisplayName,
    pub r#type: AccountType,
    pub email: Option<String>,
    pub created_by_client_id: Option<ClientId>,
}

impl NewAccount {
    /// A guest minted by `created_by` through the guest grant: no
    /// credentials, no email, and the generated name `Guest <number>`, where
    /// `number` is drawn by [`next_guest_number`] so no two guests share it.
    pub fn guest(created_by: ClientId, number: i64) -> Self {
        Self {
            id: Uuid::new_v4(),
            display_name: guest_display_name(number),
            r#type: AccountType::Guest,
            email: None,
            created_by_client_id: Some(created_by),
        }
    }

    /// A full account. Email stays optional — registration only asks for a
    /// display name.
    pub fn full(display_name: DisplayName) -> Self {
        Self {
            id: Uuid::new_v4(),
            display_name,
            r#type: AccountType::Full,
            email: None,
            created_by_client_id: None,
        }
    }

    /// Uses an id chosen by the caller instead of the generated one. Passkey
    /// registration needs this: the id travels to the authenticator when the
    /// ceremony starts, the row is written when it finishes.
    #[must_use]
    pub fn with_id(mut self, id: Uuid) -> Self {
        self.id = id;
        self
    }

    #[must_use]
    pub fn with_email(mut self, email: impl Into<String>) -> Self {
        self.email = Some(email.into());
        self
    }
}

/// `Guest <number>` as a [`DisplayName`]. The prefix, a space and the digits
/// of an `i64` are a valid label well inside its length cap, so the
/// construction cannot fail.
fn guest_display_name(number: i64) -> DisplayName {
    DisplayName::try_new(format!("{GUEST_DISPLAY_NAME_PREFIX} {number}"))
        .expect("a generated guest name is a valid display name")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::display_name;

    fn client_id() -> ClientId {
        ClientId::try_new("ligretto").unwrap()
    }

    #[test]
    fn a_new_guest_has_a_generated_name_no_email_and_its_client() {
        let guest = NewAccount::guest(client_id(), 42);

        assert_eq!(guest.r#type, AccountType::Guest);
        assert_eq!(guest.display_name.as_ref(), "Guest 42");
        assert_eq!(guest.email, None);
        assert_eq!(guest.created_by_client_id, Some(client_id()));
    }

    /// Different numbers, different names; and the widest number still fits.
    #[test]
    fn guests_with_different_numbers_have_different_names() {
        let first = NewAccount::guest(client_id(), 1);
        let second = NewAccount::guest(client_id(), 2);

        assert_ne!(first.display_name, second.display_name);
        assert_eq!(
            NewAccount::guest(client_id(), i64::MAX)
                .display_name
                .as_ref(),
            format!("Guest {}", i64::MAX)
        );
    }

    #[test]
    fn a_new_full_account_has_no_client() {
        assert_eq!(
            NewAccount::full(display_name("Ada")).created_by_client_id,
            None
        );
    }

    fn account(r#type: AccountType) -> Account {
        Account {
            id: Uuid::new_v4(),
            display_name: display_name("Ada"),
            r#type,
            email: None,
            created_by_client_id: None,
            created_at: OffsetDateTime::UNIX_EPOCH,
            last_seen_at: OffsetDateTime::UNIX_EPOCH,
        }
    }

    /// Whatever the column holds, a guest has chosen no name.
    #[test]
    fn only_a_full_account_has_a_chosen_name() {
        assert_eq!(
            account(AccountType::Full).chosen_name(),
            Some(&display_name("Ada"))
        );
        assert_eq!(account(AccountType::Guest).chosen_name(), None);
    }
}
