name: "Deploy to s3"
description: "Sync files with s3 bucket"
inputs:
  path-to-folder:
    required: true
    description: "Path to dist folder"
  AWS_ACCESS_KEY_ID:
    required: true
    description: 'AWS_ACCESS_KEY_ID'
  AWS_SECRET_ACCESS_KEY:
    required: true
    description: 'AWS_SECRET_ACCESS_KEY'
  bucket:
    required: true
    description: 's3 bucket to sync'
  AWS_REGION:
    required: false
    description: 'AWS region'
    default: 'ru-central1'

runs:
  using: "composite"
  steps:
    - name: Configure AWS
      shell: 'bash'
      run: |
        mkdir ~/.aws
        cat << 'EOF' > ~/.aws/credentials
          [default]
            aws_access_key_id = ${{ inputs.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key = ${{ inputs.AWS_SECRET_ACCESS_KEY }}
            endpoint_url = https://storage.yandexcloud.net
        EOF

        cat << 'EOF' > ~/.aws/config
          [default]
            region = ${{ inputs.AWS_REGION }}
        EOF

    - name: Upload frontend build to s3
      shell: 'bash'
      env:
        PROD_CLIENT_APP_S3_BUCKET: ${{ inputs.bucket }}
      run: |
        aws s3 sync ${{ inputs.path-to-folder }} s3://$PROD_CLIENT_APP_S3_BUCKET --delete
