CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE ONLY games
  ALTER COLUMN id SET DEFAULT uuid_generate_v4(),
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ONLY rounds
  ALTER COLUMN id SET DEFAULT uuid_generate_v4(),
  ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

CREATE OR REPLACE FUNCTION update_updated_at()
  RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER rounds_update_updated_at_trigger
  BEFORE UPDATE ON rounds
  FOR EACH ROW
EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER games_update_updated_at_trigger
  BEFORE UPDATE ON games
  FOR EACH ROW
EXECUTE FUNCTION update_updated_at();
