version: "3.3"
services:
  blog:
    image: ghcr.io/memebattle/blog:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.blog.rule=Host(`blog.mems.fun`)"
        - "traefik.http.routers.blog.entrypoints=web"
        - "traefik.http.services.blog.loadbalancer.server.port=3000"
        - "traefik.http.services.blog.loadbalancer.passhostheader=true"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  traefik-public:
    external: true
