version: '3.3'
services:
  gamehub-client:
    image: ghcr.io/memebattle/gamehub-client:latest
    ports:
      - "4000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
