version: '3.3'
services:
  ligretto-frontend:
    image: ghcr.io/memebattle/ligretto-frontend:latest
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-gameplay-backend:
    image: ghcr.io/memebattle/ligretto-gameplay-backend:latest
    ports:
      - "3005:3005"
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-gameplay-backend/key.pem
    environment:
      - LIGRETTO_GAMEPLAY_CAS_KEY_PATH=/ligretto-gameplay-backend/key.pem
      - LIGRETTO_CORE_URL=http://ligretto-core-backend:3333
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-core-backend:
    image: ghcr.io/memebattle/ligretto-core-backend:latest
    ports:
      - "3333:3333"
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-core-backend/key.pem
    environment:
      - LIGRETTO_CORE_CAS_PUBLIC_KEY_PATH=/ligretto-core-backend/key.pem
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - LIGRETTO_CORE_APP_KEY=BYnNsw-r-ndJTCy15Uqo8JAF4ONCA4X1
      - CAS_PARTNER_ID=61587c1bdc151b004107a2b5
      - CAS_URL=https://cas.mems.fun/api
      - LIGRETTO_CORE_DB_CONNECTION=pg
      - LIGRETTO_CORE_PG_HOST=ligretto-core-pg
      - LIGRETTO_CORE_PG_PORT=5432
      - LIGRETTO_CORE_PG_USER=ligretto-core-user
      - LIGRETTO_CORE_PG_PASSWORD=ligretto_pg_password
      - LIGRETTO_CORE_PG_DB_NAME=ligretto-core
      - LIGRETTO_CORE_APP_NAME=ligretto-core-backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-core-pg:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ligretto_pg_password
      POSTGRES_USER: ligretto-core-user
      POSTGRES_DB: ligretto-core
    volumes:
      - ligretto-core-pg:/var/lib/postgresql/data
  ligretto-ui:
    image: ghcr.io/memebattle/ligretto-ui:latest
    ports:
      - "3001:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
secrets:
  LIGRETTO_CAS_KEY:
    external: true
volumes:
  ligretto-core-pg:
