version: "3.3"
services:
  ligretto-gameplay-backend:
    image: ghcr.io/memebattle/ligretto-gameplay-backend:latest
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-gameplay-backend/key.pem
    environment:
      - LIGRETTO_GAMEPLAY_CAS_KEY_PATH=/ligretto-gameplay-backend/key.pem
      - LIGRETTO_CORE_URL=http://ligretto-core-backend:3333/api
      - LIGRETTO_GAMEPLAY_SOCKET_PORT=3005
    labels:
      prometheus-job: ligretto-gameplay-backend
    networks:
      - ligretto_net
      - traefik-public
      - metrics-targets
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ligretto-gameplay-backend.rule=Host(`api.ligretto.app`)"
        - "traefik.http.routers.ligretto-gameplay-backend.entrypoints=web"
        - "traefik.http.services.ligretto-gameplay-backend.loadbalancer.server.port=3005"
        - "traefik.http.services.ligretto-gameplay-backend.loadbalancer.passhostheader=true"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-core-backend:
    image: ghcr.io/memebattle/ligretto-core-backend:latest
    networks:
      - ligretto_net
      - traefik-public
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-core-backend/key.pem
    environment:
      - LIGRETTO_CORE_CAS_PUBLIC_KEY_PATH=/ligretto-core-backend/key.pem
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - LIGRETTO_CORE_APP_KEY=BYnNsw-r-ndJTCy15Uqo8JAF4ONCA4X1
      - CAS_PARTNER_ID=63b567bfd594b5085866649a
      - CAS_URL=https://cas.mems.fun/api
      - LIGRETTO_CORE_DB_CONNECTION=pg
      - LIGRETTO_CORE_PG_HOST=ligretto-core-pg
      - LIGRETTO_CORE_PG_PORT=5432
      - LIGRETTO_CORE_PG_USER=ligretto-core-user
      - LIGRETTO_CORE_PG_PASSWORD=ligretto_pg_password
      - LIGRETTO_CORE_PG_DB_NAME=ligretto-core
      - LIGRETTO_CORE_APP_NAME=ligretto-core-backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ligretto-core-backend.rule=Host(`core.ligretto.app`)"
        - "traefik.http.routers.ligretto-core-backend.entrypoints=web"
        - "traefik.http.services.ligretto-core-backend.loadbalancer.server.port=3333"
        - "traefik.http.services.ligretto-core-backend.loadbalancer.passhostheader=true"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-core-pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ligretto_pg_password
      POSTGRES_USER: ligretto-core-user
      POSTGRES_DB: ligretto-core
    networks:
      - ligretto_net
    volumes:
      - ligretto-core-pg:/var/lib/postgresql/data

secrets:
  LIGRETTO_CAS_KEY:
    external: true

volumes:
  ligretto-core-pg:

networks:
  traefik-public:
    external: true
  metrics-targets:
    external: true
  ligretto_net:
    driver: overlay
