version: "3.3"
services:
  ligretto-gameplay-backend:
    image: ghcr.io/memebattle/ligretto-gameplay-backend:latest
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-gameplay-backend/key.pem
    environment:
      - LIGRETTO_GAMEPLAY_CAS_KEY_PATH=/ligretto-gameplay-backend/key.pem
      - LIGRETTO_CORE_URL=http://ligretto-core-backend:3333/api
      - LIGRETTO_GAMEPLAY_SOCKET_PORT=3005
    networks:
      - ligretto_net
      - traefik-public
      - metrics-targets
    deploy:
      labels:
        - "prometheus-job=ligretto-gameplay-backend"
        - "prometheus-port=3005"
        - "traefik.enable=true"
        - "traefik.http.routers.ligretto-gameplay-backend.rule=Host(`api.ligretto.app`)"
        - "traefik.http.routers.ligretto-gameplay-backend.entrypoints=websecure"
        - "traefik.http.routers.ligretto-gameplay-backend.tls=true"
        - "traefik.http.services.ligretto-gameplay-backend.loadbalancer.server.port=3005"
        - "traefik.http.services.ligretto-gameplay-backend.loadbalancer.passhostheader=true"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
  ligretto-core-backend:
    image: ghcr.io/memebattle/ligretto-core-backend:latest
    networks:
      - ligretto_net
      - traefik-public
    secrets:
      - source: LIGRETTO_CAS_KEY
        target: /ligretto-core-backend/key.pem
      - source: LIGRETTO_PRODUCTION_ENV
        target: /memebattle/.env.production.local
    environment:
      - LIGRETTO_CORE_CAS_PUBLIC_KEY_PATH=/ligretto-core-backend/key.pem
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - LIGRETTO_CORE_APP_KEY=BYnNsw-r-ndJTCy15Uqo8JAF4ONCA4X1
      - CAS_PARTNER_ID=652468293877db2de8390fa3
      - CAS_URL=https://cas.mems.fun/api
      - LIGRETTO_CORE_APP_NAME=ligretto-core-backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ligretto-core-backend.rule=Host(`core.ligretto.app`)"
        - "traefik.http.routers.ligretto-core-backend.entrypoints=websecure"
        - "traefik.http.routers.ligretto-core-backend.tls=true"
        - "traefik.http.services.ligretto-core-backend.loadbalancer.server.port=3333"
        - "traefik.http.services.ligretto-core-backend.loadbalancer.passhostheader=true"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  ligretto-bot-clj:
    image: ghcr.io/memebattle/ligretto-bot-clj:latest
    networks:
      - ligretto_net
      - traefik-public
      - metrics-targets
    environment:
      - APP_PORT=3222
      - APP_HOST=0.0.0.0
    deploy:
      labels:
        - "prometheus-job=ligretto-bot-clj"
        - "prometheus-port=8080"
        - "traefik.enable=true"
        - "traefik.http.routers.ligretto-bot-clj.rule=Host(`bots.ligretto.app`)"
        - "traefik.http.routers.ligretto-bot-clj.entrypoints=websecure"
        - "traefik.http.routers.ligretto-bot-clj.tls=true"
        - "traefik.http.services.ligretto-bot-clj.loadbalancer.server.port=3222"
        - "traefik.http.services.ligretto-bot-clj.loadbalancer.passhostheader=true"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

secrets:
  LIGRETTO_CAS_KEY:
    external: true
  LIGRETTO_PRODUCTION_ENV:
    external: true

networks:
  traefik-public:
    external: true
  metrics-targets:
    external: true
  ligretto_net:
    driver: overlay
