//! Accounts — the identity root of CAS.
//!
//! An account id is the OIDC `sub`. Guests are ordinary rows
//! (`type = AccountType::Guest`) so sessions, `/me` and userinfo have a single
//! code path for guests and full accounts; a guest that registers a passkey is
//! upgraded in place, keeping its `sub`. See `docs/PLAN.md`.

use nutype::nutype;
use precis_profiles::{
    Nickname,
    precis_core::{self, profile::PrecisFastInvocation},
};
use sqlx::PgPool;
use time::OffsetDateTime;
use uuid::Uuid;

/// Upper bound on a display name, in characters. Long enough for a real name,
/// short enough to keep the sign-in UI and the authenticator prompt readable.
pub const MAX_DISPLAY_NAME_LENGTH: usize = 64;

/// Why a string is not a [`DisplayName`].
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DisplayNameError {
    #[error("must not be empty")]
    Empty,

    #[error("must be at most {MAX_DISPLAY_NAME_LENGTH} characters")]
    TooLong,

    /// A code point the PRECIS Nickname profile disallows: controls, invisible
    /// format characters (zero-width space, bidi overrides), unassigned code
    /// points. `position` is its index in the sanitised value.
    #[error("must not contain the character at position {position}")]
    DisallowedCharacter { position: usize },
}

/// Unicode general category Zs: the space separators. RFC 8266 maps every one
/// of them to ASCII space; `precis-profiles` 0.1 drops the non-ASCII ones
/// instead ("Ada\u{a0}Lovelace" would become "AdaLovelace"), so the mapping
/// is done here before the profile runs.
fn is_space_separator(c: char) -> bool {
    const EN_QUAD_TO_HAIR_SPACE: std::ops::RangeInclusive<char> = '\u{2000}'..='\u{200a}';
    matches!(
        c,
        '\u{20}' | '\u{a0}' | '\u{1680}' | '\u{202f}' | '\u{205f}' | '\u{3000}'
    ) || EN_QUAD_TO_HAIR_SPACE.contains(&c)
}

/// Applies the PRECIS Nickname profile (RFC 8266): NFKC normalisation, every
/// space mapped to ASCII space, leading and trailing spaces removed, runs of
/// spaces collapsed. A value the profile rejects is passed on unchanged so
/// that validation reports why.
fn sanitize_display_name(value: String) -> String {
    let value: String = value
        .chars()
        .map(|c| if is_space_separator(c) { ' ' } else { c })
        .collect();
    match Nickname::enforce(value.as_str()) {
        Ok(enforced) => enforced.into_owned(),
        Err(_) => value,
    }
}

fn validate_display_name(value: &str) -> Result<(), DisplayNameError> {
    match Nickname::enforce(value) {
        Ok(enforced) if enforced.is_empty() => Err(DisplayNameError::Empty),
        Ok(enforced) if enforced.chars().count() > MAX_DISPLAY_NAME_LENGTH => {
            Err(DisplayNameError::TooLong)
        }
        Ok(_) => Ok(()),
        Err(precis_core::Error::BadCodepoint(info)) => Err(DisplayNameError::DisallowedCharacter {
            position: info.position,
        }),
        // The Nickname profile only fails otherwise on a value that is empty
        // once mapped.
        Err(_) => Err(DisplayNameError::Empty),
    }
}

/// A user-facing name, valid by construction.
///
/// Sanitised and validated by the PRECIS Nickname profile plus a length cap,
/// so every UI and every authenticator prompt can show it as-is: no control
/// or invisible characters, no bidi tricks, no leading or doubled spaces.
/// Deserialising re-validates, so a stored or received value is as safe as a
/// freshly constructed one.
#[nutype(
    sanitize(with = sanitize_display_name),
    validate(with = validate_display_name, error = DisplayNameError),
    derive(Debug, Clone, PartialEq, Eq, AsRef, Deref, Display, Into, Serialize, Deserialize),
)]
pub struct DisplayName(String);

/// Whether an account has credentials of its own.
///
/// Maps to the Postgres `account_type` enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, sqlx::Type)]
#[sqlx(type_name = "account_type", rename_all = "lowercase")]
pub enum AccountType {
    /// Temporary identity created without any user interaction.
    Guest,
    /// Account with at least one credential (a passkey).
    Full,
}

/// A row of `accounts`.
#[derive(Debug, Clone, PartialEq, Eq, sqlx::FromRow)]
pub struct Account {
    /// Stable account id, exposed as the OIDC `sub`.
    pub id: Uuid,
    /// Non-unique: CAS has no username in v1. Always a valid [`DisplayName`];
    /// kept as a plain string because the row, not the reader, guarantees it.
    pub display_name: String,
    pub r#type: AccountType,
    /// Optional and unverified in v1; the future recovery anchor.
    pub email: Option<String>,
    pub created_at: OffsetDateTime,
    /// Refreshed on activity; drives guest GC.
    pub last_seen_at: OffsetDateTime,
}

/// The values a caller supplies when creating an account. `created_at` and
/// `last_seen_at` are assigned by the database.
#[derive(Debug, Clone)]
pub struct NewAccount {
    /// Generated by CAS, not by the database: passkey registration hands the id
    /// to the authenticator as the WebAuthn user handle before the row exists.
    /// The handle is baked into the credential and can never change, and
    /// discoverable login (#666) gets it back as the account to sign in.
    /// Defaults to a fresh v4 uuid; [`NewAccount::with_id`] pins a chosen one.
    pub id: Uuid,
    pub display_name: DisplayName,
    pub r#type: AccountType,
    pub email: Option<String>,
}

impl NewAccount {
    /// A guest: no credentials, no email.
    pub fn guest(display_name: DisplayName) -> Self {
        Self {
            id: Uuid::new_v4(),
            display_name,
            r#type: AccountType::Guest,
            email: None,
        }
    }

    /// A full account. Email stays optional — registration only asks for a
    /// display name.
    pub fn full(display_name: DisplayName) -> Self {
        Self {
            id: Uuid::new_v4(),
            display_name,
            r#type: AccountType::Full,
            email: None,
        }
    }

    /// Uses an id chosen by the caller instead of the generated one. Passkey
    /// registration needs this: the id travels to the authenticator when the
    /// ceremony starts, the row is written when it finishes.
    #[must_use]
    pub fn with_id(mut self, id: Uuid) -> Self {
        self.id = id;
        self
    }

    #[must_use]
    pub fn with_email(mut self, email: impl Into<String>) -> Self {
        self.email = Some(email.into());
        self
    }
}

/// Inserts an account with any executor — a pool, or the transaction that
/// registration uses to write an account and its first passkey together.
pub(crate) async fn insert<'e, E>(executor: E, account: NewAccount) -> Result<Account, sqlx::Error>
where
    E: sqlx::PgExecutor<'e>,
{
    let display_name: String = account.display_name.into();

    sqlx::query_as!(
        Account,
        r#"INSERT INTO accounts (id, display_name, type, email)
           VALUES ($1, $2, $3, $4)
           RETURNING
               id,
               display_name,
               type AS "type: AccountType",
               email,
               created_at,
               last_seen_at"#,
        account.id,
        display_name,
        account.r#type as AccountType,
        account.email,
    )
    .fetch_one(executor)
    .await
}

/// Data access for `accounts`.
#[derive(Debug, Clone)]
pub struct AccountRepository {
    pool: PgPool,
}

impl AccountRepository {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }

    /// Inserts an account and returns the stored row, including the
    /// database-assigned timestamps.
    pub async fn create(&self, account: NewAccount) -> Result<Account, sqlx::Error> {
        insert(&self.pool, account).await
    }

    /// Looks an account up by id. `Ok(None)` means no such account.
    pub async fn get(&self, id: Uuid) -> Result<Option<Account>, sqlx::Error> {
        sqlx::query_as!(
            Account,
            r#"SELECT
                   id,
                   display_name,
                   type AS "type: AccountType",
                   email,
                   created_at,
                   last_seen_at
               FROM accounts
               WHERE id = $1"#,
            id,
        )
        .fetch_optional(&self.pool)
        .await
    }
}

#[cfg(test)]
mod display_name_tests {
    use super::*;

    fn name(value: &str) -> Result<String, DisplayNameError> {
        DisplayName::try_new(value).map(Into::into)
    }

    #[test]
    fn keeps_an_ordinary_name() {
        assert_eq!(name("Ada Lovelace"), Ok("Ada Lovelace".to_owned()));
        assert_eq!(name("Ада"), Ok("Ада".to_owned()));
        assert_eq!(name("Ada 🚀"), Ok("Ada 🚀".to_owned()));
    }

    #[test]
    fn trims_and_collapses_spaces() {
        assert_eq!(name("  Ada   Lovelace  "), Ok("Ada Lovelace".to_owned()));
        // Non-ASCII spaces become ASCII ones and collapse with them.
        assert_eq!(name("Ada\u{a0}Lovelace"), Ok("Ada Lovelace".to_owned()));
        assert_eq!(
            name("Ada\u{3000} \u{2003}Lovelace"),
            Ok("Ada Lovelace".to_owned())
        );
        assert_eq!(name("\u{a0}Ada\u{a0}"), Ok("Ada".to_owned()));
    }

    #[test]
    fn normalises_compatibility_forms() {
        // Fullwidth letters are the same name as their ASCII form.
        assert_eq!(name("Ａda"), Ok("Ada".to_owned()));
    }

    #[test]
    fn rejects_empty_names() {
        assert_eq!(name(""), Err(DisplayNameError::Empty));
        assert_eq!(name("   "), Err(DisplayNameError::Empty));
    }

    #[test]
    fn rejects_names_over_the_limit() {
        assert!(name(&"a".repeat(MAX_DISPLAY_NAME_LENGTH)).is_ok());
        assert_eq!(
            name(&"a".repeat(MAX_DISPLAY_NAME_LENGTH + 1)),
            Err(DisplayNameError::TooLong)
        );
    }

    /// Invisible and direction-changing characters would let a name render as
    /// empty or as another name in the authenticator prompt.
    #[test]
    fn rejects_control_and_format_characters() {
        for value in [
            "Ada\u{7}",
            "\u{200b}",
            "Ada\u{200b}",
            "\u{202e}adA",
            "\u{feff}Ada",
        ] {
            assert!(
                matches!(
                    name(value),
                    Err(DisplayNameError::DisallowedCharacter { .. })
                ),
                "{value:?} must be rejected"
            );
        }
    }

    #[test]
    fn deserialising_validates() {
        let error = serde_json::from_str::<DisplayName>("\"\"").unwrap_err();
        assert!(error.to_string().contains("must not be empty"));

        let ok: DisplayName = serde_json::from_str("\"  Ada  \"").unwrap();
        assert_eq!(ok.as_ref(), "Ada");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::display_name;

    #[sqlx::test]
    async fn creates_a_full_account_with_an_email(pool: PgPool) {
        let repository = AccountRepository::new(pool);

        let account = repository
            .create(NewAccount::full(display_name("Ada")).with_email("ada@example.com"))
            .await
            .unwrap();

        assert_eq!(account.display_name, "Ada");
        assert_eq!(account.r#type, AccountType::Full);
        assert_eq!(account.email.as_deref(), Some("ada@example.com"));
        // A fresh account has never been seen after its creation.
        assert_eq!(account.last_seen_at, account.created_at);
    }

    #[sqlx::test]
    async fn creates_a_guest_without_an_email(pool: PgPool) {
        let repository = AccountRepository::new(pool);

        let account = repository
            .create(NewAccount::guest(display_name("Guest")))
            .await
            .unwrap();

        assert_eq!(account.r#type, AccountType::Guest);
        assert_eq!(account.email, None);
    }

    #[sqlx::test]
    async fn get_returns_the_created_account(pool: PgPool) {
        let repository = AccountRepository::new(pool);
        let created = repository
            .create(NewAccount::full(display_name("Grace")))
            .await
            .unwrap();

        let found = repository.get(created.id).await.unwrap();

        assert_eq!(found, Some(created));
    }

    #[sqlx::test]
    async fn get_returns_none_for_an_unknown_id(pool: PgPool) {
        let repository = AccountRepository::new(pool);

        let found = repository.get(Uuid::new_v4()).await.unwrap();

        assert_eq!(found, None);
    }

    #[sqlx::test]
    async fn creates_an_account_with_a_caller_chosen_id(pool: PgPool) {
        let repository = AccountRepository::new(pool);
        let id = Uuid::new_v4();

        let account = repository
            .create(NewAccount::full(display_name("Ada")).with_id(id))
            .await
            .unwrap();

        assert_eq!(account.id, id);
    }

    /// v1 has no username: two accounts may share a display name.
    #[sqlx::test]
    async fn display_names_are_not_unique(pool: PgPool) {
        let repository = AccountRepository::new(pool);

        let first = repository
            .create(NewAccount::full(display_name("Ada")))
            .await
            .unwrap();
        let second = repository
            .create(NewAccount::full(display_name("Ada")))
            .await
            .unwrap();

        assert_ne!(first.id, second.id);
    }
}
