name: 'GameHub pull request'

on:
  pull_request:
    branches: [master]
    paths:
      - 'apps/gamehub-client/**'
      - '.docker/GameHub**'
      - '.github/workflows/gamehub**'
      - 'pnpm-lock.yaml'
      - package.json
      - pnpm-workspace.yaml

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  typecheck:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/prepare-nodejs
        name: Prepare Node.js

      - name: TS check
        run: pnpm run --filter @memebattle/gamehub-client ts-check
